### PR TITLE
Add AtomicSequencePulseTemplate

### PR DESCRIPTION
**Pull request by peendebak**
Add pulse template similar to the `SequencePulseTemplate`, but which acts as an atomic pulse template.

@terrorfisch

### CODE REVIEW

**Comment by terrorfisch** [comment]
Do you have a usecase where the `to_single_waveform` of `create_program` argument does not work? I included it so you can translate arbitrary pulse template combinations to waveforms but I guess it is a bit tedious to use.

**Comment by peendebak** [comment]
> Do you have a usecase where the `to_single_waveform` of `create_program` argument does not work? I included it so you can translate arbitrary pulse template combinations to waveforms but I guess it is a bit tedious to use.

The use case for us is the following. We have a standard initialization-manipulation-readout exeperiment. The initialization and readout and in the order of microseconds and we can round durations to fit with the AWG. The manipulation stage is more time critical, so we work with ns pulses and at the end wrap the whole manipulation stage in a `AtomicSequencePT`. 

Converting the whole sequence with `to_single_waveform` would not work, since that sequence is too long. (we need the pulses in the initialization stage to be optimized by the AWG backend)

@terrorfisch

**Comment by terrorfisch** [comment]
My approach to this problem would be to use a `SequencePT` with an identifier so it doesnt get merged with the rest. It would then look like this

```python
experiment = initialization @ SequencePT(manipulation_1, manipulation_2, ..., identifier='manipulation_whatever') @ readout
program = experiment_pt.create_program(to_single_waveform={'manipulation_whatever'})
```

Alternatively one can create all `SequencePT`s explicitly and pass the pulse template since only the `@` operator merges them.
```python
manipulation = SequencePT(manipulation_1, manipulation_2, ...)
experiment = SequencePT(initialization, manipulation, readout)
program = experiment_pt.create_program(to_single_waveform={manipulation})
```

**Comment by peendebak** [comment]
@terrorfisch I was not aware of that functionality in the `create_program`. It does mean that the right arguments (e.g. `to_single_waveform={manipulation}`) have to be passed to the location(s) where `create_program` is used. That does happen in the plotting routines, although there we don't care whether the pulse is atomic or not. The other location is where the pulses are rendered by the AWG driver.
I will think about whether this approach works for us.

**Comment by terrorfisch** [comment]
Yes. The idea is to keep the hardware requirement that some pulse parts should be concatenated into a single waveform reasonably seperate from the pulse itself to make pulses more portable and be more flexible when rearranging them.

**Comment by peendebak** [comment]
Closing this PR. We will keep the `AtomicSequencePulseTemplate` in our local codebase

**Pull request closed without merging**
