### PR TITLE
Tabor segment deduplication

### LINKED ISSUE #795: Tabor: redundant waveform upload
When uplading a program which for some reason has multiple segments of equal waveforms in a `TaborProgram`, the `_find_place_for_segments_in_memory`-function does not check for unique values but uploads all segments from this batch of segments regardless. 
It seems to me thast this may be preventable by checking for unique hashes. Is this assumption correct?

### PR DESCRIPTION
**Pull request by terrorfisch**
Should fix #795 

 - [x] test with simulator

### CODE REVIEW

**Comment by terrorfisch** [comment]
@Nomos11 Can you test if this works?

**Comment by Nomos11** [comment]
so far it seems to give me an IndexError at `to_upload_size = np.sum(new_segment_lengths[unknown] + 16)`, which implies that it still tries to find places for all redundant waveforms, I'll investigate that further

**Comment by Nomos11** [comment]
It seems like the segment_lengths need to be adapted to throw out duplicates, which should be fixable relatively easily

**Comment by terrorfisch** [comment]
Does it work now?

**Comment by Nomos11** [comment]
From looking at the code I am a bit confused - does cutting off the array choose the correct values? the segment_lengths can contain subsequent duplicate values, which are not thrown out here, giving the incorrect values to my understanding

**Comment by terrorfisch** [comment]
You are right. I did not think it through.

**Comment by terrorfisch** [comment]
@Nomos11 Should work now

**Pull request merged**
