### PR TITLE
Zurich instruments HDAWG driver

### PR DESCRIPTION
**Pull request by terrorfisch**
PROBLEMS:
- Long programs take forever (approx.) to compile
- Short waveforms lead to tiing issues if sequenced by a complex program with many instructions

TODO:
 - [x] Offset handling
 - [x] Utilize `playWaveformIndexed` with for loops to shorten seqc programs
 - [x] Increase minimal Waveform length (to 192 samples?). The exact minimal length depends on the choosen translation pattern.
 - [x] Basic tests for AWG class

Implements #431

### CODE REVIEW

**Comment by peendebak** [comment]
@ekammerloher @terrorfisch The following example (modified from `zihdawg.py`) fails for me:
```
hdawg.reset()

entry_list_zero = [(0, 0), (100e-9, 0, 'hold')]
entry_list_step = [(0, 0), (50e-9, .5, 'hold'), (100e-9, 0, 'hold')]
marker_start = TablePT({'P1': entry_list_zero,  'marker': entry_list_step})
tpt1 = TablePT({'P1': entry_list_zero, 'marker': entry_list_zero})
spt2 = SequencePT(marker_start, tpt1)
    
p = spt2.create_program()

ch = ('P1', None)
mk = ('marker', None)
voltage_transform = (lambda x: x,)*len(ch)
hdawg.channel_pair_AB.upload('table_pulse_test5', p, ch, mk, voltage_transform) 
```
The PR itself works nice. I will continue testing. 

Will there be besides the `channel_pair_AB` also a `channel_pair_ABCDEFGH` for when the channel grouping of the HDAWG8 is set to 8x1?

**Comment by terrorfisch** [comment]
> Will there be besides the channel_pair_AB also a channel_pair_ABCDEFGH for when the channel grouping of the HDAWG8 is set to 8x1?
As far as I remember from talking to a ZI engineer, the sequencer program will be duplicated to the 4 sequencers if one uses the 8x1 mode. I think the only downside of pushing the program to the four channel pairs seperatly is that we need to compile it four times (unless we optimize this and hash the program structure). Or is there anything that I miss?

**Comment by ekammerloher** [comment]
The last 5 commits were not tested on the HDAWG yet, so the failing example
is not a big surprise to me.
I don't have access to the HDAWG at the moment, but will try to fix it soon.

**Comment by peendebak** [comment]
> > Will there be besides the channel_pair_AB also a channel_pair_ABCDEFGH for when the channel grouping of the HDAWG8 is set to 8x1?
> 
> As far as I remember from talking to a ZI engineer, the sequencer program will be duplicated to the 4 sequencers if one uses the 8x1 mode. I think the only downside of pushing the program to the four channel pairs seperatly is that we need to compile it four times (unless we optimize this and hash the program structure). Or is there anything that I miss?

It takes a little bit more effort from the user to use the 4 channel pairs, otherwise I am not yet aware of other downsides.

**Comment by peendebak** [comment]
@terrorfisch @ekammerloher Is seems this driver accepts Pulses that are defined with seconds as the unit for the time domain. In general qupulse works with ns as the unit. Should we change this to ns? if not, iis there a method to change the unit of the time domian from ns to s (and back)?

And: is there already a slack channel for qupulse?

**Comment by ekammerloher** [comment]
@peendebak I made the driver accept pulses defined in nanoseconds, to be consistent with the rest of qupulse.

**Comment by peendebak** [comment]
@ekammerloher There is already a driver in QCoDeS that creates `Parameter`s for all properties of the HDAWG8. Is it an option to use that for setting various properties? 

See https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/ZI/ZIHDAWG8.py

I already used both this PR and that driver together and that seems to work.

**Comment by eendebakpt** [comment]
The driver fails for a `FunctioPT`. Here is a minimal example:
```
hdawg = HDAWGRepresentation(address)

pulse=TablePT( {'P1': [(0,0), (100,.1), (200,.2),(300,0)]}, identifier='table') # works
pulse=FunctionPT( '.001', 500, channel='P1', identifier='functionpt_constant') # works
pulse=FunctionPT( '.001+t', 500, channel='P1', identifier='functionpt') # fails

p = pulse.create_program()
voltage_transform = (lambda x: x,)*2

hdawg.channel_pair_AB.upload('zi_test'+pulse.identifier, p, ['P1', None], [None,None], voltage_transform)
```
@ekammerloher @terrorfisch

**Comment by terrorfisch** [comment]
Strange. I will try to reproduce it today. What is the error massage?

**Comment by peendebak** [comment]
@terrorfisch 
```
Traceback (most recent call last):

  File "<ipython-input-11-bf0595862b71>", line 12, in <module>
    hdawg.channel_pair_AB.upload('zi_test'+pulse.identifier, p, ['P1', None], [None,None], voltage_transform)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 326, in upload
    force)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 679, in register
    '\n'.join(seqc_gen))

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 708, in program_to_seqc
    for line in self.program_to_seqc(child):

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 705, in program_to_seqc
    yield template.format(self.waveform_to_seqc(prog.waveform))

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 722, in waveform_to_seqc
    self._overwrite)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\hardware\awgs\zihdawg.py", line 589, in register
    voltage = voltage_transformation[idx](waveform.get_sampled(chan, sample_times))

  File "d:\users\eendebakpt\projects\qupulse\qupulse\_program\waveforms.py", line 90, in get_sampled
    result = self.unsafe_sample(channel, sample_times)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\_program\waveforms.py", line 269, in unsafe_sample
    output_array[:] = self._expression.evaluate_numeric(t=sample_times)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\expressions.py", line 77, in evaluate_numeric
    return self._parse_evaluate_numeric_result(result, kwargs)

  File "d:\users\eendebakpt\projects\qupulse\qupulse\expressions.py", line 61, in _parse_evaluate_numeric_result
    raise NonNumericEvaluation(self, result, call_arguments)

NonNumericEvaluation: The result of evaluate_numeric is of type object which is not a number
```

**Comment by terrorfisch** [comment]
@peendebak I was not able to test these changes yet, but they should fix the bug you found.

**Comment by terrorfisch** [comment]
I think we sould have some rudimentary tests. I'd like to keep the test coverage above 90%.

**Comment by terrorfisch** [comment]
#483 tackles parts of this

**Pull request merged**
