### PR TITLE
Feat/mfli driver

### PR DESCRIPTION
**Pull request by terrorfisch**

### CODE REVIEW

**Comment by paulsurrey** [comment]
@terrorfisch only for testing things.

**Comment by terrorfisch** [comment]
@paulsurrey should we focus on moving this forward?

**Comment by terrorfisch** [comment]
What do you think about utilizing https://github.com/mwouts/jupytext/ to manage the examples?

**Comment by terrorfisch** [comment]
I think we should create a separate repository for this in the spirit of #779

**Comment by terrorfisch** [comment]
Will be moved to a seperate repository

**Pull request closed without merging**
