### PR TITLE
add measurement windows for pulse arithmetic

### PR DESCRIPTION
**Pull request by peendebak**
We combine the measurement windows from the `lhs` and `rhs` if these are templates. For expressions or numbers there are no windows.

@terrorfisch

### CODE REVIEW

**Comment by terrorfisch** [comment]
What is you usecase for `get_measurement_windows`? I had to dig into my old code to remember that I originally intended the function to be only used locally i.e. only return the measurement windows defined by `self`, not by its children. The only intended use right now is in `_internal_create_program`. Therefore only composed `AtomicPulseTemplate`s like `ArithmeticAtomicPulseTemplate` and `AtomicMultiChannelPulseTemplate` need to redefine them because their childrens measurement windows would otherwise be neglected during program instantiation.

However, I think that there are some inconsistencies here. I am unsure why there is an implementation for `MappingPulseTemplate`. But `MappingPulseTemplate` is somehow a special case.

If you need a function to collect all measurements that are defined by a `PulseTemplate` AND its children without instantiating it via `create_program` we should add a seperate function for that.

**Comment by eendebakpt** [comment]
@terrorfisch I don't really have a use case, I just got an error when I used pulse arithmetic related to the missing `get_measurement_windows` and solved it this way. An alternative would be to return just an empty set of measurement windows.
But suppose someone added a measurement window to some pulse and somewhere later the pulse gets multiplied by a scalar (e.g. an attenuation in the fridge), then one would want the measurement window to be kept I think.

**Comment by eendebakpt** [comment]
@terrorfisch The pulse that triggered the error was:
``` 
In [5]: pulse
Out[5]: SequencePulseTemplate(subtemplates=[SequencePulseTemplate(subtemplates=[((Expression(0) + AtomicMultiChannelPulseTemplate(subtemplates=[ConstantPulseTemplate(name='constant_pulse',duration=Expression(119.99999999999999)), MappingPulseTemplate(template=AtomicMultiChannelPulseTemplate(subtemplates=[FunctionPulseTemplate(duration_expression=Expression('duration'),expression=Expression('(amplitude*(1-heaviside(padding-t, 0))*heaviside((duration-padding_after)-t, 0))*cos(2*pi*domega*t+phase+0)'),channel='I',measurements=[],parameter_constraints=[]), FunctionPulseTemplate(duration_expression=Expression('duration'),expression=Expression('(amplitude*(1-heaviside(padding-t, 0))*heaviside((duration-padding_after)-t, 0))*cos(2*pi*domega*t+phase+-1.5707963267948966)'),channel='Q',measurements=[],parameter_constraints=[]), TablePulseTemplate(entries={'P': [(0, 1.0, 'hold'), (119.99999999999999, 1.0, 'hold')]},parameter_constraints=[],measurements=[])]),parameter_mapping=_FrozenDictByWrapping({'duration': Expression(119.99999999999999), 'amplitude': Expression(0.9), 'domega': Expression(-0.06), 'padding': Expression(0.0), 'padding_after': Expression(0.0), 'phase': Expression(0.0)}),channel_mapping={'I': 'I', 'P': 'P', 'Q': 'Q'})])) '+' AtomicMultiChannelPulseTemplate(subtemplates=[ConstantPulseTemplate(name='constant_pulse',duration=Expression(119.99999999999999)), MappingPulseTemplate(template=AtomicMultiChannelPulseTemplate(subtemplates=[FunctionPulseTemplate(duration_expression=Expression('duration'),expression=Expression('(amplitude*(1-heaviside(padding-t, 0))*heaviside((duration-padding_after)-t, 0))*cos(2*pi*domega*t+phase+0)'),channel='I',measurements=[],parameter_constraints=[]), FunctionPulseTemplate(duration_expression=Expression('duration'),expression=Expression('(amplitude*(1-heaviside(padding-t, 0))*heaviside((duration-padding_after)-t, 0))*cos(2*pi*domega*t+phase+-1.5707963267948966)'),channel='Q',measurements=[],parameter_constraints=[]), TablePulseTemplate(entries={'P': [(0, 1.0, 'hold'), (119.99999999999999, 1.0, 'hold')]},parameter_constraints=[],measurements=[])]),parameter_mapping=_FrozenDictByWrapping({'duration': Expression(119.99999999999999), 'amplitude': Expression(0.8), 'domega': Expression(0.04), 'padding': Expression(0.0), 'padding_after': Expression(0.0), 'phase': Expression(0.0)}),channel_mapping={'I': 'I', 'P': 'P', 'Q': 'Q'})]))])])
``` 
The error was triggered by plotting the pulse.
```
In [6]: plot_pulse(pulse, fig=2, sample_rate=2.4, plot_channels=['I', 'Q', 'P'])
Traceback (most recent call last):

  File "<ipython-input-6-9757ef3c844f>", line 1, in <module>
    plot_pulse(p, fig=2, sample_rate=2.4, plot_channels=['I', 'Q', 'P'])

  File "c:\projects\sqt\src\sqt\measurements\pulse_generator.py", line 121, in plot_pulse
    _ = plot(pulse, sample_rate=sample_rate, axes=plt.gca(), **kwargs)

  File "c:\projects\qupulse\qupulse\pulses\plotting.py", line 160, in plot
    program = pulse.create_program(parameters=parameters,

  File "c:\projects\qupulse\qupulse\pulses\pulse_template.py", line 159, in create_program
    self._create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\pulse_template.py", line 230, in _create_program
    self._internal_create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\sequence_pulse_template.py", line 153, in _internal_create_program
    subtemplate._create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\pulse_template.py", line 230, in _create_program
    self._internal_create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\sequence_pulse_template.py", line 153, in _internal_create_program
    subtemplate._create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\pulse_template.py", line 230, in _create_program
    self._internal_create_program(scope=scope,

  File "c:\projects\qupulse\qupulse\pulses\pulse_template.py", line 325, in _internal_create_program
    measurements = self.get_measurement_windows(parameters=scope,

  File "c:\projects\qupulse\qupulse\pulses\arithmetic_pulse_template.py", line 136, in get_measurement_windows
    measurements.extend(self.lhs.get_measurement_windows(parameters=parameters,

AttributeError: 'ArithmeticPulseTemplate' object has no attribute 'get_measurement_windows'
```

**Comment by terrorfisch** [comment]
Ah, I think I understand the problem now and I created an issue for the underlying cause #578. Thank you for uncovering this and the fix!

Can you add this to the method to avoid that new external code will depend on it?
```python
if not getattr(inspect.getmodule(inspect.stack()[1][0]), '__name__', '').startswith('qupulse'):
    warnings.warn("This is only a hack until https://github.com/qutech/qupulse/issues/578 is resolved. "
                  "Do not call this method directly", category=DeprecationWarning, stacklevel=2)
```

**Comment by peendebak** [comment]
@terrorfisch Done!

**Pull request merged**
